### ISSUE TITLE
Empty lists

### ISSUE THREAD

**Issue by Jluisito** [matueranet/kanboard-import-trello#7] opened 2016-07-01 09:05 UTC
Hi,
I can execute the script and it creates a project in Kanboard with the same name that the board in Trello and with the same lists, but these lists are empty.
When I execute the script everything seems ok. There is no errors, and the prompt says "Adding cards", but no cards are created in Kanboard.

Can you help me?
Thanks!

**Comment by Jluisito** [comment] 2016-07-01 09:26
It seems that the instruction 
`$taskId = $client->createTask($params);`
is not working properly. I'm doing a echo of $taskId after this code and is empty.
I'm using Kanboard 1.0.30. 
Maybe there have been changes in the core of Kanboard and the script is not working now?

**Comment by khampf** [comment] 2016-07-04 10:42
I have the same problem and $params seems ok but $taskId is always 0. Will try resetting jsnorpc token and investigate further

**Comment by khampf** [comment] 2016-07-04 11:59
Commenting out the parameter 'owner_id' somewhere close to line 177 makes everyting work

```
if ($userId !== null) {
    $params['owner_id'] = $userId;
}
```

I also decided to add some error reporting by using:

```
$taskId = $client->createTask($params);
if (!$taskId) {
  printf("ERROR! taskid = %d\n", $taskId);
  print_r($params);
  return;
}
```

So I think it is the kanboard API that has problems. Should check the developer version

**Comment by Jluisito** [comment] 2016-07-06 10:54
Great @khampf !
Commenting the line 177 everything works. Maybe the problem is that the script is trying to assign the task in Kanboard to the same users that exists in Trello. If these users don't exists in Kanboard the script fails?

**Comment by khampf** [comment] 2016-07-06 12:03
If you give no user ID it defaults to 1 but should be null. But if you give an ID or even a username (it gets looked up) it is the correct ID but creation fails. After looking at the kanboard API it looks like it is done right so I think the problem is in the kanboard API itself and might have been fixed in later dev versions

**Comment by danships** [comment] 2016-09-03 18:55
I have taken your suggestion and disabled that specific piece of code in the master.

**Closed as completed by danships** 2016-09-03 18:55 UTC
